# Generated by Django 5.0.2 on 2024-02-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitrazh',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
