# Generated by Django 5.0.2 on 2024-02-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_vitrazh_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitrazh',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
