# Generated by Django 5.0.2 on 2024-03-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_vitrazh_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('biography', models.TextField(max_length=255, verbose_name='О себе')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Мастер',
            },
        ),
        migrations.AlterModelOptions(
            name='vitrazh',
            options={'verbose_name': 'Витражи', 'verbose_name_plural': 'Витражи'},
        ),
        migrations.AlterField(
            model_name='vitrazh',
            name='description',
            field=models.TextField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='vitrazh',
            name='image',
            field=models.ImageField(upload_to='photos/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='vitrazh',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
