# Generated by Django 5.0.2 on 2024-04-01 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_kontakt_delete_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kontakt',
            new_name='Contact',
        ),
    ]
