# Generated by Django 5.0.2 on 2024-04-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_rename_kontakt_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('one', models.TextField(verbose_name='Первый абзац')),
                ('two', models.TextField(verbose_name='Второй абзац')),
                ('three', models.TextField(verbose_name='Третий абзац')),
                ('four', models.TextField(verbose_name='Четвертый абзац')),
                ('five', models.TextField(verbose_name='Пятый абзац')),
                ('six', models.TextField(verbose_name='Шестой абзац')),
                ('seven', models.TextField(verbose_name='Седьмой абзац')),
                ('eight', models.TextField(verbose_name='Восьмой абзац')),
                ('nine', models.TextField(verbose_name='Девятый абзац')),
                ('ten', models.TextField(verbose_name='Десятый абзац')),
            ],
            options={
                'verbose_name': 'Главная',
                'verbose_name_plural': 'Главная',
            },
        ),
    ]
